spring:
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/sql_test?serverTimezone=UTC&useUnicode=TRUE&characterEncoding=utf-8&useSSL=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver
#    需要配置
#  redis:
#    host: 121.5.52.221
#    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl